name: MLOps CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Data Processing
        run:  |
          python src/data/run_processing.py \
            --input data/raw/house_data.csv \
            --output data/processed/cleaned_house_data.csv

      - name: Feature Engineering
        run: |
          python src/features/engineer.py \
            --input data/processed/cleaned_house_data.csv \
            --output data/processed/featured_house_data.csv \
            --preprocessor models/trained/preprocessor.pkl
      
            
      - name: Start up MLFlow
        run: |
          docker run -d --name mlflow-server -p 5555:5000 ghcr.io/mlflow/mlflow:latest \
          mlflow server \
          --host 0.0.0.0 \
          --backend-store-uri sqlite:///mlflow.db \
          --default-artifact-root /tmp/mlruns


      - name: Model training
        run: |
          python src/models/train_model.py \
            --config configs/model_config.yaml \
            --data data/processed/featured_house_data.csv \
            --models-dir models \
            --mlflow-tracking-uri http://localhost:5555

              
      - name: Stop MLFlow
        run: |
          docker stop mlflow-server
          docker rm mlflow-server
          docker rmi ghcr.io/mlflow/mlflow:latest


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: schmetz/fastapi:{{github.sha}}
          context: "."
          file: "Dockerfile"